title: "A Starter Blog"
description: A starter blog based on Long Form Jekyll theme built with SASS

baseurl: "/blog"     # set to "" for user/organization site; "/repo" for project site
url: "https://jdalbey.github.io"

paginate_path: "blog/page:num/"
permalink: blog/:title/

# theme isn't needed cause I provide layout, includes, assets, etc.
# theme: minima

collections: {}
exclude: ["README.md"]
# Header Option
header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: Archive
      url: /archive/
    - title: About
      url: /about
    - title: Contact
      url: /contact

social:
    email: jdalbey@e.email


